import { assert, test } from 'vitest';
import { isGeneratedFile } from './generatedFileDetection';

test('isGeneratedFile detects @generated in block comment', () => {
  const content = `/**
 * @generated by common/src/codegen/generateCommands.ts
 */
export class Foo {}
`;
  assert.isTrue(isGeneratedFile(content));
});

test('isGeneratedFile detects @generated in single-line comment', () => {
  const content = `// @generated
export class Foo {}
`;
  assert.isTrue(isGeneratedFile(content));
});

test('isGeneratedFile detects @generated with surrounding text', () => {
  const content = `/**
 * Generated Command: Retrieve an Item entry
 *
 * @generated by common/src/codegen/generateCommands.ts
 * To modify what is generated, edit the generator, not this file.
 */
export class Foo {}
`;
  assert.isTrue(isGeneratedFile(content));
});

test('isGeneratedFile returns false for normal files', () => {
  const content = `import { foo } from './bar';

export function doStuff() {
  return foo();
}
`;
  assert.isFalse(isGeneratedFile(content));
});

test('isGeneratedFile returns false when @generated appears in code, not comments', () => {
  const content = `const tag = '@generated';
export function doStuff() {}
`;
  assert.isFalse(isGeneratedFile(content));
});

test('isGeneratedFile returns false for empty file', () => {
  assert.isFalse(isGeneratedFile(''));
});

test('isGeneratedFile returns false when @generated appears in prose within a line comment', () => {
  /*
    Regression test: comments like "// Skip files marked as @generated"
    should NOT trigger detection. The @generated marker must be the PRIMARY
    content of the comment, not embedded in prose.
  */
  const content = `import { foo } from './bar';

// Skip files marked as @generated
export function doStuff() {
  return foo();
}
`;
  assert.isFalse(
    isGeneratedFile(content),
    'Should not detect @generated in prose within a line comment',
  );
});

test('isGeneratedFile returns false when @generated appears in prose within a block comment', () => {
  const content = `/**
 * Utility to check if a file is marked as @generated.
 * This is part of the file detection logic.
 */
export function doStuff() {
  return true;
}
`;
  assert.isFalse(
    isGeneratedFile(content),
    'Should not detect @generated in prose within a block comment',
  );
});
